### ISSUE TITLE
Prev month 

### ISSUE THREAD

**Issue by gr33n-made** [Dissarion/lesson3#1]
Hi!
You are getting previous month with

> last_month_number = today_month_number - 1 # предыдущий месяц

But did you think about, for example January?

**Comment by gr33n-made** [comment]
Same stuff i can tell you about next lines:

> days_in_last_month = dt.date(today_year_number, today_month_number, 1) - dt.date(today_year_number, last_month_number, 1)
It would not work in January. Think about Timedeltas

**Comment by Dissarion** [comment]
Fixed. If the month is January, it takes December
